source 'https://rubygems.org'
ruby '2.3.4'

# https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L263
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.2'#, '>= 5.0.0.1'
gem 'pg'
gem 'puma', '~> 3.0'
gem 'jbuilder', '~> 2.5'
gem 'devise', github: 'micapam/devise', ref: 'e42d40c6'
gem 'two_factor_authentication', github: 'Houdini/two_factor_authentication'
gem 'rqrcode-rails3', github: 'micapam/rqrcode-rails3'
gem 'mini_magick'
gem 'devise_invitable'
gem 'maildown'
gem 'redcarpet'
gem 'activerecord-session_store'
gem 'rollbar', '~> 2.14'
gem 'telstra-sms'
gem 'uglifier', '>= 1.3.0'
gem 'rolify'
gem 'cancancan'
gem 'rubyXL'
gem 'draper'
gem 'jquery-rails'
gem 'confstruct'
gem 'kaminari'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'dotenv-rails', github: 'govau/dotenv', ref: 'd7c1f64'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rspec-rails'
  gem 'fabrication'
  gem 'rails-controller-testing'
  gem 'rspec_junit_formatter'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'capybara'
  # gem 'codecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
