/* eslint-disable max-len */

// Different length text is used like so:
// name: shows in an indicator card and as the
// title of a chart (or in the legend for stacked charts)
// shortDescription: shows on the axis of a chart
// longDescription: shows in the tooltip for a chart
export default {
  population: {
    name: 'Population',
    shortDescription: 'Total population',
    longDescription: 'This shows the population size.\n\nSource: ABS - Regional Population Growth',
    format: '0[.]0a',
    contextual: true,
    lastUpdated: '2016',
    source: 'Population, All persons, People',
  },
  growthRate: {
    name: 'Annual population growth rate',
    shortDescription: 'Annual growth',
    longDescription: 'This shows the percentage change in the level of the population on the preceding year.\n\nSource: ABS - Regional Population Growth',
    format: '0[.]0%',
    contextual: true,
    lastUpdated: '2016',
    source: 'Population, persons, Annual Growth %',
  },
  indigenousPopulation: {
    name: 'Indigenous population',
    shortDescription: 'Indigenous status, percentage of total population',
    longDescription: 'This shows the proportion of the population that identifies as Aboriginal or Torres Strait Islander.\n\nSource: ABS - Census 2016',
    format: '0[.]0%',
    contextual: true,
    lastUpdated: '2016',
    source: 'Indigenous status, % of population',
  },
  population10yr: {
    name: 'Average annual population growth over 10 years',
    shortDescription: 'Average growth over 10 years',
    longDescription: 'This shows the average annual percentage change in the size of the population over the past ten years.\n\nSource: ABS - Regional Population Growth',
    format: '0[.]0%',
    contextual: true,
    lastUpdated: '2016',
    source: 'Population, persons, 10-year Growth %',
  },
  householdSize: {
    name: 'Average household size',
    shortDescription: 'Household size',
    longDescription: 'This shows the average number of people per occupied dwelling.Source: ABS - Census 2016',
    format: '0[.]0',
    contextual: true,
    lastUpdated: '2016',
    source: 'Average Household Size, People per household',
  },
  medianHousePrice: {
    name: 'Median house price',
    shortDescription: 'Median house price',
    longDescription: 'This shows the median price over 12 months for detached dwellings.\n\nSource: CoreLogic ',
    format: '$0,0[.]00a',
    contextual: true,
    lastUpdated: '2017',
    source: 'Median housing price, AUD',
  },
  householdIncome: {
    name: 'Median annual household income',
    shortDescription: 'Median annual household income',
    longDescription: 'THis shows the median annual household income.\n\nSource: ABS - Census 2016',
    format: '$0,0a',
    contextual: true,
    lastUpdated: '2016',
    source: 'Median Household Income, AUD per year',
  },
  lifeExpectancy: {
    name: 'Life expectancy at birth',
    shortDescription: 'Life expectancy',
    longDescription: 'This shows the number of years a person born today is expected to live.\n\nSource: ABS - Life Tables, States, Territories and Australia',
    format: '0,0a',
    contextual: true,
    lastUpdated: '2016',
    source: 'Life expectancy, All persons, years',
  },
  shareInBottomIncomeQuintile: {
    name: 'Share in bottom household income quintile',
    shortDescription: 'Share in bottom household income quintile',
    longDescription: 'This shows the share of households in bottom 20% of the national household income distribution.\n\nSource: ABS - Census 2016',
    format: '0[.]0%',
    contextual: true,
    lastUpdated: '2016',
    source: 'Share of households in lowest national income quintile, % of households',
  },
  socioEconomicIndex: {
    name: 'Socio-economic indexes for areas',
    shortDescription: 'Socio-economic indexes for areas',
    longDescription: 'This shows an index of relative socio-economic disadvantage. A low score indicates relatively greater disadvantage.\n\nSource: ABS - Census 2011',
    format: '$0,0[.]0a',
    contextual: true,
    lastUpdated: '2011',
    source: 'Socio-Economic Indexes for Areas, Index of Relative Socio-economic Disadvantage, Index',
  },
  goodsProducingSector: {
    name: 'Goods producing sector',
    shortDescription: 'Goods producing sector',
    longDescription: 'This shows the proportion of employed persons that work in goods producing industries.\n\nSource: ABS - Labour Force',
    format: '0[.]%',
    contextual: true,
    lastUpdated: '2017',
    source: 'Goods Producing Sector, % of jobs in city',
  },
  marketServices: {
    name: 'Market services',
    shortDescription: 'Market services',
    longDescription: 'This shows the proportion of employed persons that work in market services industries.\n\nSource: ABS - Labour Force',
    format: '0[.]%',
    contextual: true,
    lastUpdated: '2017',
    source: 'Market Services, % of jobs in city',
  },
  nonMarketServices: {
    name: 'Non-market services',
    shortDescription: 'Non-market services',
    longDescription: 'This shows the proportion of employed persons that work in non-market service industries.\n\nSource: ABS: Labour Force ',
    format: '0[.]%',
    contextual: true,
    lastUpdated: '2017',
    source: 'Non-market Services, % of jobs in city',
  },
  participationRateGeneral: {
    name: 'General participation rate',
    shortDescription: 'All persons',
    longDescription: 'This shows the share of the civilian population in the labour force. \n\nSource: ABS - Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Participation rate, all persons, % of population aged over 15 years',
  },
  participationRateMale: {
    name: 'Male participation rate',
    shortDescription: 'Male',
    longDescription: 'This shows the share of the civilian population in the labour force that are male. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Participation rate, Male, % of population aged over 15 years',
  },
  participationRateFemale: {
    name: 'Female participation rate',
    shortDescription: 'Female',
    longDescription: 'This shows the share of the civilian population in the labour force that are female. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Participation rate, Female, % of population aged over 15 years',
  },
  educationalAttainmentYr12: {
    name: 'Educational attainment: year 12',
    shortDescription: 'Year 12',
    longDescription: 'This shows the proportion of a city’s population that have completed year 12. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Education attainment - Completed Year 12, % of population',
  },
  educationalAttainmentCertificate: {
    name: 'Educational attainment: certificate',
    shortDescription: 'Certificate',
    longDescription: 'This shows the proportion of a city’s population that have completed certificate Level III qualifications or higher. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Education attainment - Completed Certificate III or IV, % of population',
  },
  educationalAttainmentTertiary: {
    name: 'Educational attainment: tertiary',
    shortDescription: 'Tertiary',
    longDescription: 'This shows the proportion of a city’s population that have completed a bachelor degree or higher. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Education attainment - Completed Bachelor Degree or Higher, % of population',
  },
  dispersion: {
    name: 'Local government dispersion',
    shortDescription: 'LGAs per 100,000 persons',
    longDescription: 'This shows the number of Local Government Areas per 100 000 persons. \n\nSource: ABS - Regional Population Growth ',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Government Dispersion, Number of Local Government Areas per 100 000 persons',
  },
  dwellingHouse: {
    name: 'Dwelling type ratio: house',
    shortDescription: 'House',
    longDescription: 'This shows the share of dwellings that are detached houses, semi detached, apartments, or other dwellings. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dwelling type ratio, Separate house, Percentage of Dwellings',
  },
  dwellingSemi: {
    name: 'Dwelling type ratio: semi-detached',
    shortDescription: 'Semi-detached',
    longDescription: 'This shows the share of dwellings that are detached houses, semi detached, apartments, or other dwellings. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dwelling type ratio, Semi-detached, Percentage of Dwellings',
  },
  dwellingApartment: {
    name: 'Dwelling type ratio: flat or apartment',
    shortDescription: 'Flat / apartment',
    longDescription: 'This shows the share of dwellings that are detached houses, semi detached, apartments, or other dwellings. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dwelling type ratio, Flat or Apartment, Percentage of Dwellings',
  },
  dwellingOther: {
    name: 'Dwelling type ratio: other',
    shortDescription: 'Other',
    longDescription: 'This shows the share of dwellings that are detached houses, semi detached, apartments, or other dwellings. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dwelling type ratio, Other, Percentage of Dwellings',
  },
  dwellingPriceToIncomeRatio: {
    name: 'Dwelling price to household income ratio',
    shortDescription: 'Dwelling price to household income ratio',
    longDescription: 'This shows the ratio of the median dwelling price to median annual household income. \n\nSource: Corelogic ',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dwelling price to income ratio, Ratio',
  },
  jobsCar: {
    name: 'Jobs accessible within 30 minutes by car',
    shortDescription: 'Proportion of jobs accessible within 30 minutes by car',
    longDescription: 'This shows the share of jobs in a city that can be reached by car in a commute of 30 minutes or less during the morning peak. \n\nSource: SGS Economics and Planning ',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Proportion of jobs accessible within 30 minutes, By Car, % of all jobs in city',
  },
  activeJourneys: {
    name: 'Active transport use',
    shortDescription: 'Proprtion of journeys to work by active transport',
    longDescription: 'This shows the proportion of journeys to work that are taken by active transport (walking or cycling). \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Active transport use, % of journeys to work',
  },
  publicJourneys: {
    name: 'Public transport use',
    shortDescription: 'Proprtion of journeys to work by public transport',
    longDescription: 'This shows the proportion of journeys to work that are taken by public transport. \n\nSource: ABS Census 2016 ',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Public transport use, % of journeys to work',
  },
  unemploymentRateGeneral: {
    name: 'General unemployment rate',
    shortDescription: 'Unemployment',
    longDescription: 'This shows the average unemployment rate for 12 months for all persons. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Unemployment rate, All persons',
  },
  unemploymentRateIndigenous: {
    name: 'Indigenous unemployment rate',
    shortDescription: 'Indigenous',
    longDescription: 'This shows the average indigenous unemployment rate for 12 months. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Unemployment rate, Unemployed, % of indigenous population',
  },
  unemploymentRateYouth: {
    name: 'Youth unemployment rate',
    shortDescription: 'Youth',
    longDescription: 'This shows the average youth unemployment rate for 12 months',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Unemployment rate, Unemployed, % of youth population',
  },
  employmentGrowth: {
    name: 'Employment growth',
    shortDescription: 'Annual growth in number of jobs',
    longDescription: 'This shows the percentage change in the level of employment in the current year compared to the previous year. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Full-time employment growth, Persons',
  },
  publicHousingUnits: {
    name: 'Public housing units',
    shortDescription: 'Public housing units per 100,000 persons',
    longDescription: 'This shows the number of public and community housing units per 100,000 people. \n\nSource: ABS Census 2016',
    format: '0,0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'Public housing, Dwelling units per 100 000 persons',
  },
  homelessnessRate: {
    name: 'Homelessness rate',
    shortDescription: 'Homelessness per 100,000 persons',
    longDescription: 'This shows the number of homeless people per 100,000 people. \n\nSource: ABS Census 2011',
    format: '0,0',
    contextual: false,
    lastUpdated: '2011',
    source: 'Homelessness, number of homeless per 100 000',
  },
  housingConstructionCosts: {
    name: 'Housing construction costs',
    shortDescription: 'Housing construction cost, $/m²',
    longDescription: 'This shows the average cost per square metre of constructing a new detached house in a city. \n\nSource: Rawlinsons Guide to Construction Costs',
    format: '$0,0a',
    contextual: false,
    lastUpdated: '2017',
    source: 'Residential construction costs, AUD per square metre',
  },
  rentStress: {
    name: 'Rent stress',
    shortDescription: 'Proportion of households under rent stress',
    longDescription: 'This shows the proportion of occupied households for which rent payments make up 30 per cent or more of household income. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Rent Stress, Proportion of households under rent stress, Dwellings',
  },
  mortgageStress: {
    name: 'Mortgage stress',
    shortDescription: 'Proportion of households under mortgage stress',
    longDescription: 'This shows the proportion of occupied households for which mortgage payments make up 30 per cent or more of household income. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Mortgage stress, Proportion of households under mortgage stress, Dwellings',
  },
  residentialBuildingApprovalsTotal: {
    name: 'Total residential building approvals',
    shortDescription: 'Total residential building approvals',
    longDescription: 'Total residential building approvals',
    format: '0,0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'Annual Building Approvals, Dwellings',
  },
  residentialBuildingApprovalsGrowth: {
    name: 'Residential building approvals and growth',
    shortDescription: 'Residential building approvals per annual population change',
    longDescription: 'This shows the ratio of annual population change to annual residential building approvals, calculated as a five-year average. \n\nSource: ABS Building Approvals 2017 ABS Regional Population Growth 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Annual Building Approvals, population change per Approvals annually, Ratio',
  },
  peakDelay: {
    name: 'Peak travel delay',
    shortDescription: 'Percentage increase in car trip duration at peak time',
    longDescription: 'This shows the percentage increase in the duration of a car trip made during the busiest traffic periods (7am to 10am and 4pm to 7pm) compared with when there is no congestion. \n\nSource: TomTom Australia',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Percentage increase in 30 minute car trip time at AM PM peak compared to no congestion, % ', // Final space in string is intentional and necessary
  },
  accessToPublicTransport: {
    name: 'Access to public transport',
    shortDescription: 'Percentage dwellings within 400m of public transport',
    longDescription: 'This shows the proportion of dwellings within 400 metres of a frequently serviced public transport stop – one with a scheduled service every 30 minutes from 7am to 7pm on a normal weekday. \n\nSource: Royal Melbourne Institute of Technology',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Access to public transport, dwellings within 400m of frequently serviced transport stop, % of dwellings',
  },
  grossParklandArea: {
    name: 'Gross parkland area',
    shortDescription: 'Percentage of gross land area that is parkland',
    longDescription: 'This shows the proportion of land area in a city that is defined as green space. \n\nSource: ABS - Australian Statistical Geography Standard',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Land area that is parkland, % of gross land area',
  },
  greenhouseGasEmissions: {
    name: 'Greenhouse gas emissions',
    shortDescription: 'Kilograms of greenhouse gas emissions per capita per year',
    longDescription: 'This shows the estimated per-capita amount of greenhouse gases emitted in a year, based on Scope 1 emissions. \n\nSource: ational Greenhouse Gas Inventory',
    format: '0[.]0a',
    contextual: false,
    lastUpdated: '2015',
    source: 'Greenhouse gas emissions  per capita, kilograms per capita per year',
  },
  accessToGreenSpace: {
    name: 'Access to green space',
    shortDescription: 'Percentage of dwellings with access to green space',
    longDescription: 'This shows the share of dwellings in a city that are located within 400 metres of green space. \n\nSource: ABS - Australian Statistical Geography Standard',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Access to green space, % of dwellings',
  },
  airPollutionPm10: {
    name: 'Air pollution, >PM10',
    shortDescription: 'Particle pollution greater than PM10',
    longDescription: 'This shows the average amount of particulate matter in a city’s air per cubic metre, measured over the course of a year for particles that are less than 10 microns in diameter. \n\nSource: World Health Organisation',
    format: '0[.]0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'Air quality, Annual mean, >PM10, ug/m3',
  },
  airPollutionPm2point5: {
    name: 'Air pollution, <PM2.5',
    shortDescription: 'Particle pollution less than PM2.5',
    longDescription: 'This shows the average amount of particulate matter in a city’s air per cubic metre, measured over the course of a year for particles that are less than 2.5 microns in diameter. \n\nSource: World Health Organisation',
    format: '0[.]0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'Air quality, Annual mean, <PM2.5, ug/m3',
  },
  energyEfficiencyOfBuildings: {
    name: 'Energy efficiency of buildings',
    shortDescription: 'Average energy efficiency rating of commercial buildings',
    longDescription: 'This shows the average National Australian Built Environment Rating System (NABERS) score for rated office buildings in the city, weighted by rated floor space. *Cities with fewer than 10 rated buildings are Albury Wodonga, Ballarat, Bendigo, Cairns, Geelong, Launceston, Mackay, Toowoomba, Townsville, Western Sydney and Sunshine Coast. \n\nSource: National Australian Built Environment Rating System',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '',
    source: 'Building energy efficiency, Average rating',
  },
  volunteeringRate: {
    name: 'Volunteering rate',
    shortDescription: 'Percentage of population over 15 years who volunteer',
    longDescription: 'This shows the share of people aged 15 years and older who volunteered their time, services or skills to a club, organisation or association in the past twelve months. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Number of volunteers, All persons, % of Persons 15 or over',
  },
  // perceivedSafety: {
  //   name: 'Perceived safety',
  //   shortDescription: 'Feelings of safety walking alone in local area after dark',
  //   longDescription: 'This shows the share of people aged 18 years and over who report that they feel safe or very safe walking alone in their local area after dark. \n\nSource: PHIDU – Social Health Atlas of Australia',
  //   format: '0[.]0%',
  //   contextual: false,
  //   lastUpdated: '2014',
  //   source: 'TODO',
  // },
  homicideRate: {
    name: 'Homicide rate',
    shortDescription: 'Homicides per 100,000 persons',
    longDescription: 'Homicides per 100,000 persons',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Violent crime rate, Homicides, Crimes against the person per 100,000',
  },
  adultObesity: {
    name: 'Adult obesity rate',
    shortDescription: 'Proportion of adults who are obese',
    longDescription: 'This shows the share of people aged 18 and over with a body mass index (BMI) greater than 30. \n\nSource: PHIDU – Social Health Atlas of Australia',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2015',
    source: 'Percentage of the adult population who are obese, Estimated population, aged 18 years and over, who were obese, % of population',
  },
  crisisSupport: {
    name: 'Support in times of crisis',
    shortDescription: 'Percentage of population able to get crisis support',
    longDescription: 'This shows the share of people that stated in a survey that they feel there is someone outside their household who could be asked for support in a time of crisis. \n\nSource: PHIDU – Social Health Atlas of Australia',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2014',
    source: 'Able to get support in times of crisis , % of population',
  },
  suicideRate: {
    name: 'Suicide rate',
    shortDescription: 'Number of suicides per 100,000 persons',
    longDescription: 'This shows the number of suicides in a year per 100,000 people, calculated over the period 2010 to 2014. \n\nSource: PHIDU – Social Health Atlas of Australia',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Suicides, per 100 000',
  },
  householdsWithBroadband: {
    name: 'Households with broadband',
    shortDescription: 'Percentage of households with broadband',
    longDescription: 'This shows the share of households in a city with an active broadband connection, defined as an access speed of 256 kilobits per second or faster. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Percentage of households with a broadband connection, Internet accessed from dwelling, % of dwellings',
  },
  patentApplications: {
    name: 'Patent applications',
    shortDescription: 'Patent applications per 100,000 persons',
    longDescription: 'This shows the number of patent applications by people resident in a city per 100,000 people per year. \n\nSource: ABS Data by Region',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Patents applications, Patent applications per 100 000',
  },
  newBusinessEntrants: {
    name: 'New business entrants',
    shortDescription: 'New business entrants',
    longDescription: 'This shows the business entry and exit rates: the number of new businesses that started actively trading on the business register over the past year as a share of the total number of registered businesses at the start of the year. \n\nSource: ABS Data by Region',
    format: '0[.]0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'New business entrants and exits, New Businesses as a share of the stock',
  },
  newBusinessExits: {
    name: 'New business exits',
    shortDescription: 'New business exits',
    longDescription: 'This shows the business entry and exit rates: the number of new businesses that started actively trading on the business register over the past year as a share of the total number of registered businesses at the start of the year. \n\nSource: ABS Data by Region',
    format: '0[.]0a',
    contextual: false,
    lastUpdated: '2016',
    source: 'New business entrants and exits, Business exits as a share of the stock',
  },
  knowledgeWorkersRatio: {
    name: 'Knowledge workers ratio',
    shortDescription: 'Percentage of employment as knowledge workers',
    longDescription: 'This shows the share of employed persons that work in the top three knowledge-intensive service industries. \n\nSource: ABS Labour Force',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2017',
    source: 'Knowledge workers, All persons, % of total employment',
  },
  linkedInConnectivityLocal: {
    name: 'LinkedIn connectivity: local',
    shortDescription: 'Local',
    longDescription: 'This shows the average share of LinkedIn account holder contacts that are located in the same city, other parts of Australia or overseas. \n\nSource: LinkedIn',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '',
    source: 'LinkedIn connectivity, Average number of connections from local area, % of connections average',
  },
  linkedInConnectivityRestOfNation: {
    name: 'LinkedIn connectivity: rest of Australia',
    shortDescription: 'National',
    longDescription: 'This shows the average share of LinkedIn account holder contacts that are located in the same city, other parts of Australia or overseas. \n\nSource: LinkedIn',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '',
    source: 'LinkedIn connectivity, Average number of connections from the rest of Australia, % of connections average',
  },
  linkedInConnectivityInternational: {
    name: 'LinkedIn connectivity: international',
    shortDescription: 'International',
    longDescription: 'This shows the average share of LinkedIn account holder contacts that are located in the same city, other parts of Australia or overseas. \n\nSource: LinkedIn',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '',
    source: 'LinkedIn connectivity, Average number of international connections, % of connections average',
  },
  localGovernmentDispersion: {
    name: 'Local government dispersion',
    shortDescription: 'Number of LGAs per 100,000 persons',
    longDescription: 'Number of Local Government Areas per 100,000 persons',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Government Dispersion, Number of Local Government Areas per 100 000 persons',
  },
  populationDensity: {
    name: 'Population density',
    shortDescription: 'Persons per square kilometre',
    longDescription: 'This shows the number of persons per square kilometre. \n\nSource: ABS - Regional Population Growth',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Population-weighted density, Persons per square kilometre',
  },
  dependencyRatioNotWorkingAge: {
    name: 'Dependency ratio: not of working age',
    shortDescription: 'Not of working age',
    longDescription: 'This shows the number of persons of non-working age (0-14 and 65+) per person of working age (15-64)',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dependency ratio, Ratio not of working age to working age, % ', // intentional space at end
  },
  dependencyRatio14OrYounger: {
    name: 'Dependency ratio: 14 or younger',
    shortDescription: '14 or younger',
    longDescription: 'This shows the share of population aged 0 to 14, 15 to 64, and 65 and over. \n\nSource: ABS - Regional Population Growth',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dependency ratio, All persons 0-14, % of population',
  },
  dependencyRatio15To64: {
    name: 'Dependency ratio: 15-64',
    shortDescription: '15-64',
    longDescription: 'This shows the share of population aged 0 to 14, 15 to 64, and 65 and over. \n\nSource: ABS - Regional Population Growth',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dependency ratio, All persons 15-64, % of population',
  },
  dependencyRatio65OrOlder: {
    name: 'Dependency ratio: 65 or older',
    shortDescription: '65 or older',
    longDescription: 'This shows the share of population aged 0 to 14, 15 to 64, and 65 and over. \n\nSource: ABS - Regional Population Growth',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dependency ratio, All persons 65+, % of population',
  },
  dependencyRatioMedianAge: {
    name: 'Dependency ratio: median age',
    shortDescription: 'Dependency ratio: median age',
    longDescription: 'This shows the median age. \n\nSource: ABS - Regional Population Growth',
    format: '0[.]0',
    contextual: false,
    lastUpdated: '2016',
    source: 'Dependency ratio, median age, All persons, years',
  },
  disabilityRate: {
    name: 'Disability rate',
    shortDescription: 'Population share with disability',
    longDescription: 'This shows the proportion of the population that self identifies as having disability. \n\nSource: ABS - Disability, Ageing and Carers',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2015',
    source: 'Disability, all persons, % of population',
  },
  tenureRatioOwnedOutright: {
    name: 'Tenure ratio: owned outright',
    shortDescription: 'Owned outright',
    longDescription: 'This shows the share of occupied private residential dwellings that are owned outright by the occupier, owned with a mortgage, are rented, or other. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Tenure ratio, Owned outright, %',
  },
  tenureRatioMortgage: {
    name: 'Tenure ratio: owned with mortgage',
    shortDescription: 'Mortgage',
    longDescription: 'This shows the share of occupied private residential dwellings that are owned outright by the occupier, owned with a mortgage, are rented, or other. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Tenure ratio, Owned with a mortgage, %',
  },
  tenureRatioRented: {
    name: 'Tenure ratio: rented',
    shortDescription: 'Rented',
    longDescription: 'This shows the share of occupied private residential dwellings that are owned outright by the occupier, owned with a mortgage, are rented, or other. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Tenure ratio, Rented, %',
  },
  tenureRatioOther: {
    name: 'Tenure ratio: other',
    shortDescription: 'Other',
    longDescription: 'This shows the share of occupied private residential dwellings that are owned outright by the occupier, owned with a mortgage, are rented, or other. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Tenure ratio, Other, %',
  },
  languagesOtherThanEnglish: {
    name: 'Languages other than English',
    shortDescription: 'Language other than English spoken at home',
    longDescription: 'This shows the proportion of residents who speak a language other than English at home. \n\nSource: ABS Census 2016',
    format: '0[.]0%',
    contextual: false,
    lastUpdated: '2016',
    source: 'Language other than English spoken at home, All persons, % of population',
  },
};
