import {
  DATA_TYPES,
  AGGREGATION_METHODS,
} from './misc';

// Different length text is used like so:
// name: shows in an indicator card and as the
// title of a chart (or in the legend for stacked charts)
// shortDescription: shows on the axis of a chart
// longDescription: shows in the tooltip for a chart
export default {
  indigenousPopulation: {
    name: 'Indigenous population',
    shortDescription: 'Indigenous population',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: true,
    source: 'Indigenous status, % of population',
  },
  population10yr: {
    name: 'Population 10 year growth rate',
    shortDescription: 'Growth rate',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: true,
    source: 'Population, persons, 10-year Growth %',
  },
  householdSize: {
    name: 'Average household size',
    shortDescription: 'Household size',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0',
    contextual: true,
    source: 'Average Household Size, People per household',
  },
  medianHousePrice: {
    name: 'Median house price',
    shortDescription: 'Median house price',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '$0,0a',
    contextual: true,
    source: 'Median housing price, AUD',
  },
  householdIncome: {
    name: 'Median annual household income',
    shortDescription: 'Median annual household income',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '$0,0a',
    contextual: true,
    source: 'Median Household Income, AUD per year',
  },
  lifeExpectancy: {
    name: 'Life expectancy at birth',
    shortDescription: 'Life expectancy',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0,0a',
    contextual: true,
    source: 'Life expectancy, All persons, years',
  },
  shareInBottomIncomeQuintile: {
    name: 'Share in bottom household income quintile',
    shortDescription: 'Share in bottom household income quintile',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: true,
    source: 'Share of households in lowest national income quintile, % of households',
  },
  socioEconomicIndex: {
    name: 'Socio economic indexes for areas',
    shortDescription: 'Socio economic indexes for areas',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0,0[.]a',
    contextual: true,
    source: 'Socio-Economic Indexes for Areas, Index of Relative Socio-economic Disadvantage, Index',
  },
  goodsProducingSector: {
    name: 'Goods producing sector',
    shortDescription: 'Goods producing sector',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]%',
    contextual: true,
    source: 'Goods Producing Sector, % of jobs in city',
  },
  marketServices: {
    name: 'Market services',
    shortDescription: 'Market services',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]%',
    contextual: true,
    source: 'Market Services, % of jobs in city',
  },
  nonMarketServices: {
    name: 'Non-market services',
    shortDescription: 'Non-market services',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]%',
    contextual: true,
    source: 'Non-market Services, % of jobs in city',
  },
  participationRateGeneral: {
    name: 'General participation rate',
    shortDescription: 'General',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Participation rate, all persons, % of population aged over 15 years',
  },
  participationRateMale: {
    name: 'Male participation rate',
    shortDescription: 'Male',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Participation rate, Male, % of population aged over 15 years',
  },
  participationRateFemale: {
    name: 'Female participation rate',
    shortDescription: 'Female',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Participation rate, Female, % of population aged over 15 years',
  },
  educationalAttainmentYr12: {
    name: 'Educational attainment - year 12',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Education attainment - Completed Year 12, % of population',
  },
  population: {
    name: 'The population',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.SUM,
    format: '0[.]0a',
    contextual: true,
    source: 'Population, All persons, People',
  },
  growthRate: {
    name: 'The growthRate',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    cardSuffix: '/year',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Population, persons, Annual Growth %',
  },
  dispersion: {
    name: 'Local government dispersion',
    shortDescription: 'Local government dispersion',
    longDescription: 'Local government dispersion',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Government Dispersion, Number of Local Government Areas per 100 000 persons',
  },
  dwellingHouse: {
    name: 'House',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Dwelling type ratio, Separate house, Percentage of Dwellings',
  },
  dwellingSemi: {
    name: 'Semi-House',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Dwelling type ratio, Semi-detached, Percentage of Dwellings',
  },
  dwellingApartment: {
    name: 'Apartment',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Dwelling type ratio, Flat or Apartment, Percentage of Dwellings',
  },
  dwellingOther: {
    name: 'Other',
    shortDescription: 'TODO',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Dwelling type ratio, Other, Percentage of Dwellings',
  },
  jobsCar: {
    name: 'Proportion of jobs accessible within 30 minutes by Car',
    shortDescription: 'Proportion of jobs accessible within 30 minutes, By Car, % of all jobs in city',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Proportion of jobs accessible within 30 minutes, By Car, % of all jobs in city',
  },
  activeJourneys: {
    name: 'Active transport use',
    shortDescription: 'Active transport use, % of journeys to work',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Active transport use, % of journeys to work',
  },
  publicJourneys: {
    name: 'Public transport use',
    shortDescription: 'Public transport use, % of journeys to work',
    longDescription: 'TODO',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Public transport use, % of journeys to work',
  },
  unemploymentRateGeneral: {
    name: 'General unemployment rate',
    shortDescription: 'General',
    longDescription: 'General',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Unemployment rate, All persons',
  },
  unemploymentRateIndigenous: {
    name: 'Indigenous unemployment rate',
    shortDescription: 'Indigenous',
    longDescription: 'Indigenous',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Unemployment rate, Unemployed, % of indigenous population',
  },
  unemploymentRateYouth: {
    name: 'Youth unemployment rate',
    shortDescription: 'Youth',
    longDescription: 'Youth',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Unemployment rate, Unemployed, % of youth population',
  },
  employmentGrowth: {
    name: 'Employment growth',
    shortDescription: 'Annual growth in number of jobs',
    longDescription: 'Annual growth in number of jobs',
    dataType: DATA_TYPES.NUMBER,
    aggregationMethod: AGGREGATION_METHODS.MEDIAN,
    format: '0[.]0%',
    contextual: false,
    source: 'Full-time employment growth, Persons',
  },
};
