export default {
  projectDefinitions: [{
    "cid": 21,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 21,
      "agency_id": 4,
      "business_category_id": 1,
      "name": "Project Program 1",
      "dimo_uid": "AGA_001",
      "kind": "Project",
      "start_date": "2015-07-01",
      "completion_date": "2017-12-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 14744906,
      "ict_budget": 183620000,
      "agency_coordinator_email": "firstname.lastname@Agency-A.gov.au",
      "agency_sro_email": "firstname.lastname@AGA_001.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 21,
      "project_id": 21,
      "assessment_collection_id": 2,
      "total_spend_to_date": 86028000,
      "time_score": "70-90%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "81.33",
      "time_percentage": "59.41",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 1,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Most risks and mitigations are NOT logical, complete or current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "A green-amber rating has been assigned as the benefits identified do not appear to have been realised after 8 years of work and operations - risks appear to have been adequately identified with mitigation and controls applied.",
      "public_impact_population": "2 - Population - Medium",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 3352,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 2,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Green-Amber",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 4, "name": "Agency A", "short_name": "AGA", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 1, "name": "Invest in National Capability and Assets"}
  }, {
    "cid": 22,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 22,
      "agency_id": 4,
      "business_category_id": 2,
      "name": "Project Program 2",
      "dimo_uid": "AGA_002",
      "kind": "Project",
      "start_date": "2011-01-11",
      "completion_date": "2017-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 32785011,
      "ict_budget": 11915000,
      "agency_coordinator_email": "firstname.lastname@Agency-A.gov.au",
      "agency_sro_email": "firstname.lastname@AGA_002.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 22,
      "project_id": 22,
      "assessment_collection_id": 2,
      "total_spend_to_date": 118060000,
      "time_score": "70-90%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "12.71",
      "time_percentage": "26.05",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 1,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "Any of the residual risks are High",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 1,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 2176,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 2,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": null,
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 4, "name": "Agency A", "short_name": "AGA", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 2, "name": "Payments Management"}
  }, {
    "cid": 23,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 23,
      "agency_id": 4,
      "business_category_id": 3,
      "name": "Project Program 3",
      "dimo_uid": "AGA_003",
      "kind": "Program",
      "start_date": "2017-01-01",
      "completion_date": "2017-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 175300000,
      "ict_budget": 212475000,
      "agency_coordinator_email": "firstname.lastname@Agency-A.gov.au",
      "agency_sro_email": "firstname.lastname@AGA_003.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 23,
      "project_id": 23,
      "assessment_collection_id": 2,
      "total_spend_to_date": 95877000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "10.08",
      "time_percentage": "89.67",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "Any of the residual risks are High",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "1 - Population - Low",
      "public_impact_quantum": "3 - Quantum - High",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1826,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 3,
      "overall_residual_risk_score": 2,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 4, "name": "Agency A", "short_name": "AGA", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 3, "name": "Service Delivery"}
  }, {
    "cid": 24,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 24,
      "agency_id": 4,
      "business_category_id": 4,
      "name": "Project Program 4",
      "dimo_uid": "AGA_004",
      "kind": "Project",
      "start_date": "2016-07-01",
      "completion_date": "2018-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 16870000,
      "ict_budget": 31138054,
      "agency_coordinator_email": "firstname.lastname@Agency-A.gov.au",
      "agency_sro_email": "firstname.lastname@AGA_004.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 24,
      "project_id": 24,
      "assessment_collection_id": 2,
      "total_spend_to_date": 118060000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "94.79",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Most risks and mitigations are NOT logical, complete or current",
      "overall_risk_residual_risks": "Any of the residual risks are Extreme OR\r\nno risks have been provided",
      "overall_risk_assessor": 5,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "No risks identified or provide.  Benefits are not identified as beings incrementally realised.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 3,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 741,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 3,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": "Red",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 4, "name": "Agency A", "short_name": "AGA", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 4, "name": "Collection of Revenue"}
  }, {
    "cid": 25,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 25,
      "agency_id": 4,
      "business_category_id": 3,
      "name": "Project Program 5",
      "dimo_uid": "AGA_005",
      "kind": "Project",
      "start_date": "2015-04-01",
      "completion_date": "2020-03-31",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 31138054,
      "ict_budget": 43690000,
      "agency_coordinator_email": "firstname.lastname@Agency-A.gov.au",
      "agency_sro_email": "firstname.lastname@AGA_005.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 25,
      "project_id": 25,
      "assessment_collection_id": 2,
      "total_spend_to_date": 0,
      "time_score": ">90%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "55.34",
      "time_percentage": "75.67",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 4,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "the project has already experienced a delay and has some potential to face more unplanned scheduling and resourcing risks",
      "public_impact_population": "1 - Population - Low",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 5,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1457,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 5,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Green-Amber",
      "delivery_confidence_agency": "Green",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 4, "name": "Agency A", "short_name": "AGA", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 3, "name": "Service Delivery"}
  }, {
    "cid": 26,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 26,
      "agency_id": 5,
      "business_category_id": 5,
      "name": "Project Program 6",
      "dimo_uid": "AGB_001",
      "kind": "Program",
      "start_date": "2016-07-01",
      "completion_date": "2017-12-31",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 101148000,
      "ict_budget": 101148000,
      "agency_coordinator_email": "firstname.lastname@Agency-B.gov.au",
      "agency_sro_email": "firstname.lastname@AGB_001.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 26,
      "project_id": 26,
      "assessment_collection_id": 2,
      "total_spend_to_date": 171088000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "94.79",
      "time_percentage": "78.3",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "2 - Population - Medium",
      "public_impact_quantum": "3 - Quantum - High",
      "public_impact_score": 5,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1460,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 3,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 5, "name": "Agency B", "short_name": "AGB", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 5, "name": "Internal Government Resource Management"}
  }, {
    "cid": 27,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 27,
      "agency_id": 5,
      "business_category_id": 6,
      "name": "Project Program 7",
      "dimo_uid": "AGB_002",
      "kind": "Project",
      "start_date": "2015-05-25",
      "completion_date": "2018-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 16870000,
      "ict_budget": 43690000,
      "agency_coordinator_email": "firstname.lastname@Agency-B.gov.au",
      "agency_sro_email": "firstname.lastname@AGB_002.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 27,
      "project_id": 27,
      "assessment_collection_id": 2,
      "total_spend_to_date": 6970000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "20.03",
      "time_percentage": "75.67",
      "overall_benefit_viability_assessor": 1,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 1,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "there is likely to be a strong impetus culturally for this project to succeed given the nature of the issues it is seeking to mitigate - ie death and injuries to AFP personnel in terrorist-related acts in recent years.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 4,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 730,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 5, "name": "Agency B", "short_name": "AGB", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 28,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 28,
      "agency_id": 5,
      "business_category_id": 1,
      "name": "Project Program 8",
      "dimo_uid": "AGB_003",
      "kind": "Project",
      "start_date": "2016-07-01",
      "completion_date": "2018-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 457370000,
      "ict_budget": 0,
      "agency_coordinator_email": "firstname.lastname@Agency-B.gov.au",
      "agency_sro_email": "firstname.lastname@AGB_003.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 28,
      "project_id": 28,
      "assessment_collection_id": 2,
      "total_spend_to_date": 11910000,
      "time_score": "70-90%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15-25%",
      "spend_percentage": "0.0",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 1,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 4,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1094,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 5, "name": "Agency B", "short_name": "AGB", "portfolio_id": 3},
    "portfolio": {"id": 3, "name": "Portfolio_I"},
    "businessCategory": {"id": 1, "name": "Invest in National Capability and Assets"}
  }, {
    "cid": 29,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 29,
      "agency_id": 6,
      "business_category_id": 4,
      "name": "Project Program 9",
      "dimo_uid": "AGC_001",
      "kind": "Project",
      "start_date": "2015-07-01",
      "completion_date": "2019-03-09",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 24680000,
      "ict_budget": 21740000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_001.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 29,
      "project_id": 29,
      "assessment_collection_id": 2,
      "total_spend_to_date": 10100000,
      "time_score": "70-90%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "94.79",
      "time_percentage": "77.39",
      "overall_benefit_viability_assessor": 1,
      "overall_benefit_status_assessor": 1,
      "overall_benefit_rating": 4,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "the project may be successfully delivered after December 2019 however no benefits will be realised before then. This creates a collective project risk in the event of a major  incident occurring affecting the AFP's ability to deliver community policing, protection, surveillance and tactical operations before project completion.",
      "public_impact_population": "1 - Population - Low",
      "public_impact_quantum": "3 - Quantum - High",
      "public_impact_score": 4,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1278,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 1,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Red",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 4, "name": "Collection of Revenue"}
  }, {
    "cid": 30,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 30,
      "agency_id": 6,
      "business_category_id": 3,
      "name": "Project Program 10",
      "dimo_uid": "AGC_002",
      "kind": "Project",
      "start_date": "2016-10-25",
      "completion_date": "2019-03-09",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 46302000,
      "ict_budget": 31138054,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_002.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 30,
      "project_id": 30,
      "assessment_collection_id": 2,
      "total_spend_to_date": 133733000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "94.79",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 5,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "2 - Population - Medium",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 4,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1034,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 3, "name": "Service Delivery"}
  }, {
    "cid": 31,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 31,
      "agency_id": 6,
      "business_category_id": 2,
      "name": "Project Program 11",
      "dimo_uid": "AGC_003",
      "kind": "Project",
      "start_date": "2013-07-01",
      "completion_date": "2017-11-06",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 11140000,
      "ict_budget": 0,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_003.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 31,
      "project_id": 31,
      "assessment_collection_id": 2,
      "total_spend_to_date": 17960000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "54.59",
      "time_percentage": "90.71",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 1,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": null,
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 3,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1702,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 1,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber-Red",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 2, "name": "Payments Management"}
  }, {
    "cid": 32,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 32,
      "agency_id": 6,
      "business_category_id": 5,
      "name": "Project Program 12",
      "dimo_uid": "AGC_004",
      "kind": "Project",
      "start_date": "2015-07-01",
      "completion_date": "2020-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 175300000,
      "ict_budget": 13550711,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_004.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 32,
      "project_id": 32,
      "assessment_collection_id": 2,
      "total_spend_to_date": 122000000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15-25%",
      "spend_percentage": "77.11",
      "time_percentage": "76.79",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "Any of the residual risks are High",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "There are a couple of risks and benefits that should be discussed, \r\nIt would be good to know the timeing of the exception report and when recommended changes would be made.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1399,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 5,
      "overall_residual_risk_score": 2,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 5, "name": "Internal Government Resource Management"}
  }, {
    "cid": 33,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 33,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 13",
      "dimo_uid": "AGC_005",
      "kind": "Program",
      "start_date": "2010-04-01",
      "completion_date": "2018-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 220450000,
      "ict_budget": 43690000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_005.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 33,
      "project_id": 33,
      "assessment_collection_id": 2,
      "total_spend_to_date": 9420000,
      "time_score": "70-90%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "36.63",
      "time_percentage": "77.39",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 4,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "Should be more information provided on non-IT technical risks not just IT technical risks, however they are significant as the lack of stability in the  ATO's IT environment has impacted all IT projects.\r\nWould like to see the risks associated with delivery of the \"what does success look like\" points, to ensure that they are tracked and managed\r\nThis project should be discussed with the ATO to check the questions outlined above.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "3 - Quantum - High",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 2098,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 2,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Green",
      "delivery_confidence_agency": "Green",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 34,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 34,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 14",
      "dimo_uid": "AGC_006",
      "kind": "Project",
      "start_date": "2013-07-01",
      "completion_date": "2020-07-28",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 89650000,
      "ict_budget": 24310497,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_006.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 34,
      "project_id": 34,
      "assessment_collection_id": 2,
      "total_spend_to_date": 9420000,
      "time_score": "50-70%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "0.0",
      "time_percentage": "77.65",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 2,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "Any of the residual risks are High",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "While DIMO will need to discuss this project further with the ATO, hopefully there can be better explenation of the questions that we currently have.\r\nThis project probably should be thought about as something that has ongoing engagment with DIMO",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1654,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 3,
      "overall_residual_risk_score": 2,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 35,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 35,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 15",
      "dimo_uid": "AGC_007",
      "kind": "Project",
      "start_date": "2015-07-01",
      "completion_date": "2018-12-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 31138054,
      "ict_budget": 21740000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_007.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 35,
      "project_id": 35,
      "assessment_collection_id": 2,
      "total_spend_to_date": 14862000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "0.0",
      "time_percentage": "59.41",
      "overall_benefit_viability_assessor": 1,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 2,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 1,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "This program is mature and clearly has a good handle on governance.\r\nThe Gateway review was rated Green.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 2740,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 3,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 36,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 36,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 16",
      "dimo_uid": "AGC_008",
      "kind": "Project",
      "start_date": "2013-04-18",
      "completion_date": "2018-04-01",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 24680000,
      "ict_budget": 18500000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_008.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 36,
      "project_id": 36,
      "assessment_collection_id": 2,
      "total_spend_to_date": 20830000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15-25%",
      "spend_percentage": "72.33",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 1,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "There are needs to be some grater focus on ATO's new Operational framework approval and also the risk of delivering the Super funds complex changes.\r\nAlso this is flaged as a DTA platform so we should ensure that it is going to deliver on the intent.",
      "public_impact_population": "2 - Population - Medium",
      "public_impact_quantum": "3 - Quantum - High",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 760,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 1,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Green-Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 37,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 37,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 17",
      "dimo_uid": "AGC_009",
      "kind": "Program",
      "start_date": "2015-05-25",
      "completion_date": "2017-09-11",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 56870000,
      "ict_budget": 0,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_009.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 37,
      "project_id": 37,
      "assessment_collection_id": 2,
      "total_spend_to_date": 5887000,
      "time_score": "50-70%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15-25%",
      "spend_percentage": "57.42",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 5,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "All risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "Any of the residual risks are High",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "the adoption of an agile methodology appears to be generating some positive outcomes for the project thus far.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 4,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1520,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 3,
      "overall_residual_risk_score": 2,
      "delivery_confidence_dimo": "Green-Amber",
      "delivery_confidence_agency": "Green",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 38,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 38,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 18",
      "dimo_uid": "AGC_010",
      "kind": "Project",
      "start_date": "2015-11-01",
      "completion_date": "2018-09-01",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 11915000,
      "ict_budget": 21740000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_010.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 38,
      "project_id": 38,
      "assessment_collection_id": 2,
      "total_spend_to_date": 14800000,
      "time_score": "50-70%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "32.22",
      "time_percentage": "81.98",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 3,
      "overall_benefit_rating": 3,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Some risks and mitigations are logical, complete and current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 2,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "Project appears to have realistic assessment of risks and benefits, and had transparently reported one of the benefits \"at risk\".  Linkages between benefits status and risk mitigations are compelling.  Internal resourcing appears to be a consistent risk them amongst Bureau projects",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "2 - Quantum - Medium",
      "public_impact_score": 2,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1827,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 5,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Green",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }, {
    "cid": 39,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 39,
      "agency_id": 6,
      "business_category_id": 3,
      "name": "Project Program 19",
      "dimo_uid": "AGC_011",
      "kind": "Project",
      "start_date": "2017-01-01",
      "completion_date": "2020-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 150000000,
      "ict_budget": 43690000,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_011.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 39,
      "project_id": 39,
      "assessment_collection_id": 2,
      "total_spend_to_date": 0,
      "time_score": "<20%",
      "time_score_note": "None",
      "ict_cost_score": "<$20m",
      "spend_time_deviation": "<>15%",
      "spend_percentage": "63.73",
      "time_percentage": "35.65",
      "overall_benefit_viability_assessor": 3,
      "overall_benefit_status_assessor": 4,
      "overall_benefit_rating": 2,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Most risks and mitigations are NOT logical, complete or current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "This project appears to be underspent, has unclear objectives and has much logical overlap with ROBUST.  Benefits and risks are vague, with unclear measurement criteria or impact statements and don't appear to have been updated since project inception.",
      "public_impact_population": "1 - Population - Low",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 4,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 2001,
      "assessment_priority": "Involve",
      "delivery_confidence_assessor_score": 1,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Amber",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 3, "name": "Service Delivery"}
  }, {
    "cid": 40,
    "dateLastUpdated": "2017-06-30",
    "project": {
      "id": 40,
      "agency_id": 6,
      "business_category_id": 6,
      "name": "Project Program 20",
      "dimo_uid": "AGC_012",
      "kind": "Program",
      "start_date": "2010-04-01",
      "completion_date": "2017-06-30",
      "objectives": "Agency generated text",
      "budget_funded": null,
      "total_budget": 32785011,
      "ict_budget": 0,
      "agency_coordinator_email": "firstname.lastname@Agency-C.gov.au",
      "agency_sro_email": "firstname.lastname@AGC_012.gov.au",
      "meta": {
        "count_benefits": 1,
        "count_benefits_at_risk_or_removed": 1,
        "count_risks": 3,
        "count_risks_at_high_or_extreme": 1,
        "count_risks_at_medium": 1,
        "count_risks_at_low": 1
      }
    },
    "projectAssessment": {
      "id": 40,
      "project_id": 40,
      "assessment_collection_id": 2,
      "total_spend_to_date": 118060000,
      "time_score": "20-50%",
      "time_score_note": "None",
      "ict_cost_score": "$20m-$100m",
      "spend_time_deviation": "<>25-50%",
      "spend_percentage": "59.0",
      "time_percentage": "29.71",
      "overall_benefit_viability_assessor": 2,
      "overall_benefit_status_assessor": 1,
      "overall_benefit_rating": 4,
      "overall_benefit_assessor_note": "Assessor generated text",
      "overall_risk_logical_complete_current": "Most risks and mitigations are NOT logical, complete or current",
      "overall_risk_residual_risks": "All of the residual risks are low or medium",
      "overall_risk_assessor": 3,
      "overall_risk_assessor_note": "Assessor generated text",
      "delivery_confidence_assessor_note": "Program appears subject to re-prioritisation and scope changes by the agency. But risks and issues don’t reflect this. Suggest closer assurance to be done.",
      "public_impact_population": "3 - Population - High",
      "public_impact_quantum": "1 - Quantum - Low",
      "public_impact_score": 5,
      "public_impact_score_note": "Assessor generated text",
      "general_note": "Assessor generated text",
      "recommendations": "Assessor generated text",
      "duration": 1826,
      "assessment_priority": "Engage",
      "delivery_confidence_assessor_score": 4,
      "overall_residual_risk_score": 1,
      "delivery_confidence_dimo": "Amber",
      "delivery_confidence_agency": "Green",
      "status_commentary_agency": "Agency generated text"
    },
    "agency": {"id": 6, "name": "Agency C", "short_name": "AGC", "portfolio_id": 4},
    "portfolio": {"id": 4, "name": "Portfolio_II"},
    "businessCategory": {"id": 6, "name": "Protect and Secure the Nation"}
  }]
}
